[package]
name = "docli"
version = "0.1.0"
authors = ["Kevin K <kbknapp@gmail.com>"]
description = "A command line interface to managing DigitalOcean infrastructure"
license = "MIT"
repository = "https://github.com/kbknapp/docli-rs.git"
documentation = "http://kbknapp.github.io/docli-rs"
readme = "README.md"
keywords = ["do", "cli", "digitalocean", "digital", "ocean"]


[dependencies]
clap = "*"

[dependencies.libdo]
# git = "https://github.com/kbknapp/libdo-rs"
path = "../libdo-rs"


# for building with nightly and unstable features
unstable=[]
